/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Project.Pages.Receipt.Detail;

import Project.Connection.Connections;
import Project.Helper.CurrencyFormat;
import Project.Pages.Receipt.KeuanganMenu;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author dicky
 */
public class DetailPengeluaran extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetailPengeluaran
     */
    CurrencyFormat formatIDCurrency = new CurrencyFormat();
    private KeuanganMenu menuKeuangan;
    public DetailPengeluaran() {
        initComponents();
        this.menuKeuangan = KeuanganMenu.instance; // ✅ sekarang aman
        getData();
    }
    
    private void getData()
    {
        // menampilkan data dari database
        try (
            Connection conn = Connections.ConnectionDB();
            PreparedStatement pstmt = conn.prepareStatement(
                "SELECT \n" +
                "    pembelian.idPembelian,\n" +
                "    pembelian.created_at ,\n" +
                "    pembelian.keterangan,\n" +
                "    pembelian.totalHarga,\n" +
                "    agen.idAgen,\n" +
                "    detail_pembelian.idDetailPembelian,\n" +
                "    detail_pembelian.idProduk,\n" +
                "    detail_pembelian.jumlah,\n" +
                "    detail_pembelian.subtotal,\n" +
                "    produk.namaProduk,\n" +
                "    produk.stok\n" + // asumsikan kamu ingin stok produk juga
                "FROM pembelian\n" +
                "JOIN agen ON pembelian.idAgen = agen.idAgen\n" +
                "JOIN detail_pembelian ON pembelian.idPembelian = detail_pembelian.idPembelian\n" +
                "JOIN produk ON detail_pembelian.idProduk = produk.idProduk WHERE pembelian.idPembelian = ?"
            );
        ) {
            String idPengeluaran = menuKeuangan.getIdPengeluaran();
            System.out.println("ID Pengeluaran: " + idPengeluaran);

            pstmt.setString(1, idPengeluaran);

            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    String created_at = rs.getString("created_at");
                    String keterangan = rs.getString("keterangan");
                    double totalHargaValue = rs.getDouble("totalHarga");

                    // Parsing tanggal
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                    LocalDateTime dateTime = LocalDateTime.parse(created_at, formatter);

                    int minute = dateTime.getMinute();
                    int hour = dateTime.getHour();
                    int dayOfMonth = dateTime.getDayOfMonth();
                    int month = dateTime.getMonthValue();

                    String codeCreatedAt = String.format("%02d%02d%02d%02d", minute, hour, dayOfMonth, month);
                    String codePengeluaran = "OUT" + codeCreatedAt + "-" + idPengeluaran;

                    String totalPengeluaran = formatIDCurrency.currencyFormat(totalHargaValue);

                    // Debugging
                    System.out.println("==========================");
                    System.out.println("Kode Pengeluaran: " + codePengeluaran);
                    System.out.println("Created At: " + created_at);
                    System.out.println("Total Pengeluaran: " + totalPengeluaran);

                    labelKodePengeluaran.setText(codePengeluaran);
                    areaKeterangan.setText(keterangan);
                    labelTotalHarga.setText(totalPengeluaran);  // gunakan yang sudah diformat
                }
            }

        } catch (SQLException | HeadlessException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelKodePengeluaran = new javax.swing.JLabel();
        labelTotalHarga = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        label_idPemasukan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaKeterangan = new javax.swing.JTextArea();

        jLabel1.setText("Detail Pengeluaran");

        jLabel2.setText("Kode Pengeluaran");

        jLabel3.setText("Keterangan:");

        labelKodePengeluaran.setText("IN-00");

        labelTotalHarga.setText("Rp 0.000");

        jLabel7.setText("Total Harga");

        btnKembali.setBackground(new java.awt.Color(255, 204, 204));
        btnKembali.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        areaKeterangan.setColumns(20);
        areaKeterangan.setRows(5);
        jScrollPane1.setViewportView(areaKeterangan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(jLabel3))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelKodePengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(label_idPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_idPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelKodePengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelTotalHarga))
                .addGap(29, 29, 29)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaKeterangan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKodePengeluaran;
    private javax.swing.JLabel labelTotalHarga;
    private javax.swing.JLabel label_idPemasukan;
    // End of variables declaration//GEN-END:variables
}
